<?php
return $fakes[ 'profile' ] = array(
	array(
		"lastName" => "Белуччи",
		"firstName" => "Моника",
		"middlename" => "Олеговна",
		"userId" => "3",
		"birthday" => "1985-05-13",
		"birthdayIsPublic" => "0",
		"sex" => "2",
		"countryId" => "1",
		"regionId" => "1",
		"districtId" => "1",
		"cityId" => "1",
		"science" => "qweqwe",
		"religion" => "sadasd",
		"sport" => "dfsdfsd",
		"music" => "wqeqwe",
		"movie" => "dsfdsfsd",
		"book" => "qweqwe",
	),
	array(
		"lastName" => "Иванов",
		"firstName" => "Иван",
		"middlename" => "Максимов",
		"userId" => "4",
		"birthday" => "1979-12-04",
		"birthdayIsPublic" => "0",
		"sex" => "1",
		"countryId" => "1",
		"regionId" => "1",
		"districtId" => "1",
		"cityId" => "1",
		"science" => "qweqwe",
		"religion" => "sadasd",
		"sport" => "dfsdfsd",
		"music" => "wqeqwe",
		"movie" => "dsfdsfsd",
		"book" => "qweqwe",
	),
	array(
		"lastName" => "Пушкин",
		"firstName" => "Александр",
		"middlename" => "Сергеевич",
		"userId" => "16",
		"birthday" => "1979-12-04",
		"birthdayIsPublic" => "0",
		"sex" => "1",
		"countryId" => "1",
		"regionId" => "1",
		"districtId" => "1",
		"cityId" => "1",
		"science" => "qweqwe",
		"religion" => "sadasd",
		"sport" => "dfsdfsd",
		"music" => "wqeqwe",
		"movie" => "dsfdsfsd",
		"book" => "qweqwe",
	),
	array(
		"lastName" => "Альба",
		"firstName" => "Джессика",
		"middlename" => "Гургеновна",
		"userId" => "18",
		"birthday" => "1979-12-04",
		"birthdayIsPublic" => "0",
		"sex" => "2",
		"countryId" => "1",
		"regionId" => "1",
		"districtId" => "1",
		"cityId" => "1",
		"science" => "qweqwe",
		"religion" => "sadasd",
		"sport" => "dfsdfsd",
		"music" => "wqeqwe",
		"movie" => "dsfdsfsd",
		"book" => "qweqwe",
	),
	array(
		"lastName" => "Пупкин",
		"firstName" => "Василий",
		"middlename" => "Вячеславович",
		"userId" => "19",
		"birthday" => "1979-12-04",
		"birthdayIsPublic" => "0",
		"sex" => "1",
		"countryId" => "1",
		"regionId" => "1",
		"districtId" => "1",
		"cityId" => "1",
		"science" => "qweqwe",
		"religion" => "sadasd",
		"sport" => "dfsdfsd",
		"music" => "wqeqwe",
		"movie" => "dsfdsfsd",
		"book" => "qweqwe",
	),
	array(
		"lastName" => "Иванов",
		"firstName" => "Сергей",
		"middlename" => "Максимов",
		"userId" => "21",
		"birthday" => "1979-12-04",
		"birthdayIsPublic" => "0",
		"sex" => "1",
		"countryId" => "1",
		"regionId" => "1",
		"districtId" => "1",
		"cityId" => "1",
		"science" => "qweqwe",
		"religion" => "sadasd",
		"sport" => "dfsdfsd",
		"music" => "wqeqwe",
		"movie" => "dsfdsfsd",
		"book" => "qweqwe",
	)
);