name: Country
fields:
  id :
    type: INT
    options:
      - "AUTO_INCREMENT"
      - "NOT NULL"
      - "PRIMARY KEY"
  title :
    type: 'VARCHAR (70)'
index:
engine: 'InnoDB'
collate: 'utf8_general_ci'