name: Faculty
fields:
  id :
    type: INT
    options:
      - "AUTO_INCREMENT"
      - "NOT NULL"
      - "PRIMARY KEY"
    form: hidden
  title :
    type: 'VARCHAR (100)'
    options:
      - "DEFAULT NULL"
    form: text
    label: "Название"
index:
engine: 'InnoDB'
collate: 'utf8_general_ci'