name: SchoolUse
fields:
  id :
    type: INT
    options:
      - "AUTO_INCREMENT"
      - "NOT NULL"
      - "PRIMARY KEY"
    form: hidden
  userId:
    object: one
    type: INT
    options:
      - "DEFAULT NULL"
    form: select
  mySchoolId:
    object: one
    type: INT
    options:
      - "DEFAULT NULL"
    form: select
  schoolId:
    object: one
    type: INT
    options:
      - "DEFAULT NULL"
    form: select
  schoolSubjectId:
    object: one
    type: INT
    options:
      - "DEFAULT NULL"
    form: select
  score :
    type: 'VARCHAR (100)'
    options:
      - "DEFAULT NULL"
    form: text
    label: "Название"
  date :
    type : 'DATETIME'
index:
engine: 'InnoDB'
collate: 'utf8_general_ci'