name: Specialty
fields:
  id :
    type: INT
    options:
      - "AUTO_INCREMENT"
      - "NOT NULL"
      - "PRIMARY KEY"
    form: hidden
  specialityCategoryId :
    object: one
    type: INT
    form: hidden
  code :
    type: INT
    form: text
    label: "Код"
  prefix:
    type: INT
    form: text
    label: "Префикс"
  title :
    type: 'VARCHAR (50)'
    form: text
    label: "Название"
  qualification :
    type : 'enum("бакалавр", "инженер", "магистр", "специалист")'
index:
engine: 'InnoDB'
collate: 'utf8_general_ci'