name: Wall
fields:
  id :
    type: INT
    options:
      - "AUTO_INCREMENT"
      - "NOT NULL"
      - "PRIMARY KEY"
  userId :
    object: one
    type: INT
  title :
    type: 'VARCHAR (50)'
  settingId:
    object: one
    type: INT
index:
  - "INDEX `userId` (`userId`)"
engine: 'InnoDB'
collate: 'utf8_general_ci'